### ISSUE TITLE
I need to contribute to your website

### ISSUE THREAD

**Issue by StylishRockz** [DataKind-BLR/covid19bharat_frontend#1]
Need to contribute to your website as a volunteer.My e- mail is 2120867gujjalamanideep@gmail.com

**Comment by StylishRockz** [comment]
@tobylunt

**Comment by kaizer1v** [comment]
Hey @StylishRockz thanks for reaching out and apologies for seeing this now. We mostly are firefighting on the [scrapers repo](https://github.com/DataKind-BLR/covid19bharat_scrapers)

Just provided write access to this repo.

**Comment by StylishRockz** [comment]
I have interest to contribute in your work in adding cases to the website
as a volunteer.
